<?php
//REMOVE EXAMPLE FROM THE FILE NAME

//DATABASE CONFIG
const DB_HOST = '';
const DB_NAME = '';
const DB_USER = '';
const DB_PASS = '';
const DB_PORT = '';


//APP CONFIG
const APP_NAME = 'CookBook';
const PATH_ROOT    = __DIR__ . '/../';
const PATH_ASSETS  = PATH_ROOT.'assets/';

//CREATE TABLE `RECIPES` (
//`ID` INT(11) NOT NULL AUTO_INCREMENT,
//  `USER_ID` INT(11) NOT NULL,
//  `TITLE` VARCHAR(50) DEFAULT NULL,
//  `IMAGE` VARCHAR(255) DEFAULT NULL,
//  `DESCRIPTION` TEXT DEFAULT NULL,
//  `INGREDIENTS` VARCHAR(255) DEFAULT NULL,
//  `PREP_TIME` INT(11) DEFAULT NULL,
//  `LEVEL` VARCHAR(50) DEFAULT NULL,
//  `CREATED_AT` DATETIME DEFAULT NULL,
//  `MODIFIED_AT` DATETIME DEFAULT NULL,
//  PRIMARY KEY (`ID`),
//  KEY `RECIPES_USER_ID_FOREIGN` (`USER_ID`),
//  CONSTRAINT `RECIPES_USER_ID_FOREIGN` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT
//) ENGINE=InnoDB DEFAULT CHARSET=utf8;



//CREATE TABLE `USERS` (
//`ID` INT(11) NOT NULL AUTO_INCREMENT,
//  `NICKNAME` VARCHAR(255) NOT NULL,
//  `EMAIL` VARCHAR(255) NOT NULL UNIQUE,
//  `PASSWORD` VARCHAR(255) NOT NULL,
//  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
//  `MODIFIED_AT` DATETIME DEFAULT NULL,
//  PRIMARY KEY (`ID`)
//) ENGINE=InnoDB DEFAULT CHARSET=utf8;